image:
- Ubuntu
- Visual Studio 2017

platform:
  - x86
  - x64
  
configuration:
- Debug
- Release

for:
  - 
    matrix:
      only:
        - configuration: Release
    build_script:
        - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=Release
        - cmake --build _builds
  - 
    matrix:
      only:
        - configuration: Debug
    build_script:
        - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=Debug
        - cmake --build _builds 

test_script:
  - ps: cd _builds
  - ctest -VV