image:
- Visual Studio 2017
- Ubuntu

platform:
  - x86
  - x64
  
configuration:
- Debug
- Release

for:
  - 
    matrix:
      only:
        - configuration: Release
    build_script:
      - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=98
      - cmake --build _builds --config Release
    test_script:
      - ps: cd _builds
      - ctest -VV -C Release
  - 
    matrix:
      only:
        - configuration: Debug
    build_script:
        - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=98
        - cmake --build _builds --config Debug
    test_script:
      - ps: cd _builds
      - ctest -VV -C Debug
