image:
- Visual Studio 2017
- Ubuntu

platform:
  - x86
  - x64
  
configuration:
- Debug
- Release

for:
  - 
    matrix:
      only:
        - configuration: Debug
    environment:
      config: Debug

  - 
    matrix:
      only:
        - configuration: Release
    environment:
      config: Release

build_script:
  - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_CXX_STANDARD=98
  - cmake --build _builds --config %configuration%

test_script:
  - ps: cd _builds
  - ctest -VV -C %configuration%