image:
- Ubuntu
- Visual Studio 2017

platform:
  - x86
  - x64
  
configuration:
- Debug
- Release

build_script:
  - cmake -H. -B_builds
  - cmake --build _builds

test_script:
  - ps: cd _builds
  - ctest -VV